[package]
name = "neutron-star"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
melior = { git = "https://github.com/phase/melior.git", branch = "pub-everywhere" }
mlir-sys = "*"
